[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Identity
[identity]
  external_providers = []

# Post-deploy hooks для автоматической инициализации БД
[[build.processing]]
  skip_processing = false

[context.production]
  command = "npm run build && echo 'Build completed, database will be initialized automatically'"

[context.deploy-preview]
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Database initialization endpoints (call after deploy)
[[redirects]]
  from = "/admin/init-db"
  to = "/.netlify/functions/init-database"
  status = 200

[[redirects]]
  from = "/admin/seed-data"
  to = "/.netlify/functions/seed-data"
  status = 200

[[redirects]]
  from = "/admin/health"
  to = "/.netlify/functions/health-check"
  status = 200

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200