export const useTimeWebSync = () => ({
  setTransactionsUpdateCallback: () => {},
  setCategoriesUpdateCallback: () => {},
  setBudgetsUpdateCallback: () => {},
  setGoalsUpdateCallback: () => {},
  setRecurringPaymentsUpdateCallback: () => {},
  addTransaction: () => {},
  updateTransaction: () => {},
  deleteTransaction: () => {},
  addCategory: () => {},
  updateCategory: () => {},
  deleteCategory: () => {},
  addBudget: () => {},
  updateBudget: () => {},
  deleteBudget: () => {},
  addGoal: () => {},
  updateGoal: () => {},
  deleteGoal: () => {},
  addRecurringPayment: () => {},
  updateRecurringPayment: () => {},
  deleteRecurringPayment: () => {},
});
